# Generated by Django 5.2.6 on 2025-10-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('bicicleta', 'Bicicleta')], max_length=20)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
